#include "Keycodes.h"
#include <SDL2/SDL_keycode.h>

namespace renderer {
    KeyCode SDLKeyCodeToRendrKeyCode (SDL_Keycode arg) {
        switch (arg) {
            case SDLK_0:
                return RENDR_0;
            case SDLK_1:
                return RENDR_1;
            case SDLK_2:
                return RENDR_2;
            case SDLK_3:
                return RENDR_3;
            case SDLK_4:
                return RENDR_4;
            case SDLK_5:
                return RENDR_5;
            case SDLK_6:
                return RENDR_6;
            case SDLK_7:
                return RENDR_7;
            case SDLK_8:
                return RENDR_8;
            case SDLK_9:
                return RENDR_9;
            case SDLK_a:
                return RENDR_a;
            case SDLK_AC_BACK:
                return RENDR_AC_BACK;
            case SDLK_AC_BOOKMARKS:
                return RENDR_AC_BOOKMARKS;
            case SDLK_AC_FORWARD:
                return RENDR_AC_FORWARD;
            case SDLK_AC_HOME:
                return RENDR_AC_HOME;
            case SDLK_AC_REFRESH:
                return RENDR_AC_REFRESH;
            case SDLK_AC_SEARCH:
                return RENDR_AC_SEARCH;
            case SDLK_AC_STOP:
                return RENDR_AC_STOP;
            case SDLK_AGAIN:
                return RENDR_AGAIN;
            case SDLK_ALTERASE:
                return RENDR_ALTERASE;
            case SDLK_QUOTE:
                return RENDR_QUOTE;
            case SDLK_APPLICATION:
                return RENDR_APPLICATION;
            case SDLK_AUDIOMUTE:
                return RENDR_AUDIOMUTE;
            case SDLK_AUDIONEXT:
                return RENDR_AUDIONEXT;
            case SDLK_AUDIOPLAY:
                return RENDR_AUDIOPLAY;
            case SDLK_AUDIOPREV:
                return RENDR_AUDIOPREV;
            case SDLK_AUDIOSTOP:
                return RENDR_AUDIOSTOP;
            case SDLK_b:
                return RENDR_b;
            case SDLK_BACKSLASH:
                return RENDR_BACKSLASH;
            case SDLK_BACKSPACE:
                return RENDR_BACKSPACE;
            case SDLK_BRIGHTNESSDOWN:
                return RENDR_BRIGHTNESSDOWN;
            case SDLK_BRIGHTNESSUP:
                return RENDR_BRIGHTNESSUP;
            case SDLK_c:
                return RENDR_c;
            case SDLK_CALCULATOR:
                return RENDR_CALCULATOR;
            case SDLK_CANCEL:
                return RENDR_CANCEL;
            case SDLK_CAPSLOCK:
                return RENDR_CAPSLOCK;
            case SDLK_CLEAR:
                return RENDR_CLEAR;
            case SDLK_CLEARAGAIN:
                return RENDR_CLEARAGAIN;
            case SDLK_COMMA:
                return RENDR_COMMA;
            case SDLK_COMPUTER:
                return RENDR_COMPUTER;
            case SDLK_COPY:
                return RENDR_COPY;
            case SDLK_CRSEL:
                return RENDR_CRSEL;
            case SDLK_CURRENCYSUBUNIT:
                return RENDR_CURRENCYSUBUNIT;
            case SDLK_CURRENCYUNIT:
                return RENDR_CURRENCYUNIT;
            case SDLK_CUT:
                return RENDR_CUT;
            case SDLK_d:
                return RENDR_d;
            case SDLK_DECIMALSEPARATOR:
                return RENDR_DECIMALSEPARATOR;
            case SDLK_DELETE:
                return RENDR_DELETE;
            case SDLK_DISPLAYSWITCH:
                return RENDR_DISPLAYSWITCH;
            case SDLK_DOWN:
                return RENDR_DOWN;
            case SDLK_e:
                return RENDR_e;
            case SDLK_EJECT:
                return RENDR_EJECT;
            case SDLK_END:
                return RENDR_END;
            case SDLK_EQUALS:
                return RENDR_EQUALS;
            case SDLK_ESCAPE:
                return RENDR_ESCAPE;
            case SDLK_EXECUTE:
                return RENDR_EXECUTE;
            case SDLK_EXSEL:
                return RENDR_EXSEL;
            case SDLK_f:
                return RENDR_f;
            case SDLK_F1:
                return RENDR_F1;
            case SDLK_F10:
                return RENDR_F10;
            case SDLK_F11:
                return RENDR_F11;
            case SDLK_F12:
                return RENDR_F12;
            case SDLK_F13:
                return RENDR_F13;
            case SDLK_F14:
                return RENDR_F14;
            case SDLK_F15:
                return RENDR_F15;
            case SDLK_F16:
                return RENDR_F16;
            case SDLK_F17:
                return RENDR_F17;
            case SDLK_F18:
                return RENDR_F18;
            case SDLK_F19:
                return RENDR_F19;
            case SDLK_F2:
                return RENDR_F2;
            case SDLK_F20:
                return RENDR_F20;
            case SDLK_F21:
                return RENDR_F21;
            case SDLK_F22:
                return RENDR_F22;
            case SDLK_F23:
                return RENDR_F23;
            case SDLK_F24:
                return RENDR_F24;
            case SDLK_F3:
                return RENDR_F3;
            case SDLK_F4:
                return RENDR_F4;
            case SDLK_F5:
                return RENDR_F5;
            case SDLK_F6:
                return RENDR_F6;
            case SDLK_F7:
                return RENDR_F7;
            case SDLK_F8:
                return RENDR_F8;
            case SDLK_F9:
                return RENDR_F9;
            case SDLK_FIND:
                return RENDR_FIND;
            case SDLK_g:
                return RENDR_g;
            case SDLK_BACKQUOTE:
                return RENDR_BACKQUOTE;
            case SDLK_h:
                return RENDR_h;
            case SDLK_HELP:
                return RENDR_HELP;
            case SDLK_HOME:
                return RENDR_HOME;
            case SDLK_i:
                return RENDR_i;
            case SDLK_INSERT:
                return RENDR_INSERT;
            case SDLK_j:
                return RENDR_j;
            case SDLK_k:
                return RENDR_k;
            case SDLK_KBDILLUMDOWN:
                return RENDR_KBDILLUMDOWN;
            case SDLK_KBDILLUMTOGGLE:
                return RENDR_KBDILLUMTOGGLE;
            case SDLK_KBDILLUMUP:
                return RENDR_KBDILLUMUP;
            case SDLK_KP_0:
                return RENDR_KP_0;
            case SDLK_KP_00:
                return RENDR_KP_00;
            case SDLK_KP_000:
                return RENDR_KP_000;
            case SDLK_KP_1:
                return RENDR_KP_1;
            case SDLK_KP_2:
                return RENDR_KP_2;
            case SDLK_KP_3:
                return RENDR_KP_3;
            case SDLK_KP_4:
                return RENDR_KP_4;
            case SDLK_KP_5:
                return RENDR_KP_5;
            case SDLK_KP_6:
                return RENDR_KP_6;
            case SDLK_KP_7:
                return RENDR_KP_7;
            case SDLK_KP_8:
                return RENDR_KP_8;
            case SDLK_KP_9:
                return RENDR_KP_9;
            case SDLK_KP_A:
                return RENDR_KP_A;
            case SDLK_KP_AMPERSAND:
                return RENDR_KP_AMPERSAND;
            case SDLK_KP_AT:
                return RENDR_KP_AT;
            case SDLK_KP_B:
                return RENDR_KP_B;
            case SDLK_KP_BACKSPACE:
                return RENDR_KP_BACKSPACE;
            case SDLK_KP_BINARY:
                return RENDR_KP_BINARY;
            case SDLK_KP_C:
                return RENDR_KP_C;
            case SDLK_KP_CLEAR:
                return RENDR_KP_CLEAR;
            case SDLK_KP_CLEARENTRY:
                return RENDR_KP_CLEARENTRY;
            case SDLK_KP_COLON:
                return RENDR_KP_COLON;
            case SDLK_KP_COMMA:
                return RENDR_KP_COMMA;
            case SDLK_KP_D:
                return RENDR_KP_D;
            case SDLK_KP_DBLAMPERSAND:
                return RENDR_KP_DBLAMPERSAND;
            case SDLK_KP_DECIMAL:
                return RENDR_KP_DECIMAL;
            case SDLK_KP_E:
                return RENDR_KP_E;
            case SDLK_KP_ENTER:
                return RENDR_KP_ENTER;
            case SDLK_KP_EQUALS:
                return RENDR_KP_EQUALS;
            case SDLK_KP_EQUALSAS400:
                return RENDR_KP_EQUALSAS400;
            case SDLK_KP_EXCLAM:
                return RENDR_KP_EXCLAM;
            case SDLK_KP_F:
                return RENDR_KP_F;
            case SDLK_KP_GREATER:
                return RENDR_KP_GREATER;
            case SDLK_KP_HASH:
                return RENDR_KP_HASH;
            case SDLK_KP_HEXADECIMAL:
                return RENDR_KP_HEXADECIMAL;
            case SDLK_KP_LEFTBRACE:
                return RENDR_KP_LEFTBRACE;
            case SDLK_KP_LEFTPAREN:
                return RENDR_KP_LEFTPAREN;
            case SDLK_KP_LESS:
                return RENDR_KP_LESS;
            case SDLK_KP_MEMADD:
                return RENDR_KP_MEMADD;
            case SDLK_KP_MEMCLEAR:
                return RENDR_KP_MEMCLEAR;
            case SDLK_KP_MEMDIVIDE:
                return RENDR_KP_MEMDIVIDE;
            case SDLK_KP_MEMMULTIPLY:
                return RENDR_KP_MEMMULTIPLY;
            case SDLK_KP_MEMRECALL:
                return RENDR_KP_MEMRECALL;
            case SDLK_KP_MEMSTORE:
                return RENDR_KP_MEMSTORE;
            case SDLK_KP_MEMSUBTRACT:
                return RENDR_KP_MEMSUBTRACT;
            case SDLK_KP_MINUS:
                return RENDR_KP_MINUS;
            case SDLK_KP_MULTIPLY:
                return RENDR_KP_MULTIPLY;
            case SDLK_KP_OCTAL:
                return RENDR_KP_OCTAL;
            case SDLK_KP_PERCENT:
                return RENDR_KP_PERCENT;
            case SDLK_KP_PERIOD:
                return RENDR_KP_PERIOD;
            case SDLK_KP_PLUS:
                return RENDR_KP_PLUS;
            case SDLK_KP_PLUSMINUS:
                return RENDR_KP_PLUSMINUS;
            case SDLK_KP_POWER:
                return RENDR_KP_POWER;
            case SDLK_KP_RIGHTBRACE:
                return RENDR_KP_RIGHTBRACE;
            case SDLK_KP_RIGHTPAREN:
                return RENDR_KP_RIGHTPAREN;
            case SDLK_KP_SPACE:
                return RENDR_KP_SPACE;
            case SDLK_KP_TAB:
                return RENDR_KP_TAB;
            case SDLK_KP_VERTICALBAR:
                return RENDR_KP_VERTICALBAR;
            case SDLK_KP_XOR:
                return RENDR_KP_XOR;
            case SDLK_l:
                return RENDR_l;
            case SDLK_LALT:
                return RENDR_LALT;
            case SDLK_LCTRL:
                return RENDR_LCTRL;
            case SDLK_LEFT:
                return RENDR_LEFT;
            case SDLK_LEFTBRACKET:
                return RENDR_LEFTBRACKET;
            case SDLK_LGUI:
                return RENDR_LGUI;
            case SDLK_LSHIFT:
                return RENDR_LSHIFT;
            case SDLK_m:
                return RENDR_m;
            case SDLK_MAIL:
                return RENDR_MAIL;
            case SDLK_MEDIASELECT:
                return RENDR_MEDIASELECT;
            case SDLK_MENU:
                return RENDR_MENU;
            case SDLK_MINUS:
                return RENDR_MINUS;
            case SDLK_MODE:
                return RENDR_MODE;
            case SDLK_MUTE:
                return RENDR_MUTE;
            case SDLK_n:
                return RENDR_n;
            case SDLK_NUMLOCKCLEAR:
                return RENDR_NUMLOCKCLEAR;
            case SDLK_o:
                return RENDR_o;
            case SDLK_OPER:
                return RENDR_OPER;
            case SDLK_OUT:
                return RENDR_OUT;
            case SDLK_p:
                return RENDR_p;
            case SDLK_PAGEDOWN:
                return RENDR_PAGEDOWN;
            case SDLK_PAGEUP:
                return RENDR_PAGEUP;
            case SDLK_PASTE:
                return RENDR_PASTE;
            case SDLK_PAUSE:
                return RENDR_PAUSE;
            case SDLK_PERIOD:
                return RENDR_PERIOD;
            case SDLK_POWER:
                return RENDR_POWER;
            case SDLK_PRINTSCREEN:
                return RENDR_PRINTSCREEN;
            case SDLK_PRIOR:
                return RENDR_PRIOR;
            case SDLK_q:
                return RENDR_q;
            case SDLK_r:
                return RENDR_r;
            case SDLK_RALT:
                return RENDR_RALT;
            case SDLK_RCTRL:
                return RENDR_RCTRL;
            case SDLK_RETURN:
                return RENDR_RETURN;
            case SDLK_RETURN2:
                return RENDR_RETURN2;
            case SDLK_RGUI:
                return RENDR_RGUI;
            case SDLK_RIGHT:
                return RENDR_RIGHT;
            case SDLK_RIGHTBRACKET:
                return RENDR_RIGHTBRACKET;
            case SDLK_RSHIFT:
                return RENDR_RSHIFT;
            case SDLK_s:
                return RENDR_s;
            case SDLK_SCROLLLOCK:
                return RENDR_SCROLLLOCK;
            case SDLK_SELECT:
                return RENDR_SELECT;
            case SDLK_SEMICOLON:
                return RENDR_SEMICOLON;
            case SDLK_SEPARATOR:
                return RENDR_SEPARATOR;
            case SDLK_SLASH:
                return RENDR_SLASH;
            case SDLK_SLEEP:
                return RENDR_SLEEP;
            case SDLK_SPACE:
                return RENDR_SPACE;
            case SDLK_STOP:
                return RENDR_STOP;
            case SDLK_SYSREQ:
                return RENDR_SYSREQ;
            case SDLK_t:
                return RENDR_t;
            case SDLK_TAB:
                return RENDR_TAB;
            case SDLK_THOUSANDSSEPARATOR:
                return RENDR_THOUSANDSSEPARATOR;
            case SDLK_u:
                return RENDR_u;
            case SDLK_UNDO:
                return RENDR_UNDO;
            case SDLK_UNKNOWN:
                return RENDR_UNKNOWN;
            case SDLK_UP:
                return RENDR_UP;
            case SDLK_v:
                return RENDR_v;
            case SDLK_VOLUMEDOWN:
                return RENDR_VOLUMEDOWN;
            case SDLK_VOLUMEUP:
                return RENDR_VOLUMEUP;
            case SDLK_w:
                return RENDR_w;
            case SDLK_WWW:
                return RENDR_WWW;
            case SDLK_x:
                return RENDR_x;
            case SDLK_y:
                return RENDR_y;
            case SDLK_z:
                return RENDR_z;
            case SDLK_AMPERSAND:
                return RENDR_AMPERSAND;
            case SDLK_ASTERISK:
                return RENDR_ASTERISK;
            case SDLK_AT:
                return RENDR_AT;
            case SDLK_CARET:
                return RENDR_CARET;
            case SDLK_COLON:
                return RENDR_COLON;
            case SDLK_DOLLAR:
                return RENDR_DOLLAR;
            case SDLK_EXCLAIM:
                return RENDR_EXCLAIM;
            case SDLK_GREATER:
                return RENDR_GREATER;
            case SDLK_HASH:
                return RENDR_HASH;
            case SDLK_LEFTPAREN:
                return RENDR_LEFTPAREN;
            case SDLK_LESS:
                return RENDR_LESS;
            case SDLK_PERCENT:
                return RENDR_PERCENT;
            case SDLK_PLUS:
                return RENDR_PLUS;
            case SDLK_QUESTION:
                return RENDR_QUESTION;
            case SDLK_QUOTEDBL:
                return RENDR_QUOTEDBL;
            case SDLK_RIGHTPAREN:
                return RENDR_RIGHTPAREN;
            case SDLK_UNDERSCORE:
                return RENDR_UNDERSCORE;
        }
    }
} // namespace renderer